// diagnose.mjs — headless load of masystem.co.in, capture console errors + body text.
import pkg from '/root/.npm/_npx/e41f203b7505f1fb/node_modules/playwright/index.js';
const { chromium } = pkg;
const url = process.argv[2] || 'https://masystem.co.in/';
const browser = await chromium.launch();
const page = await browser.newPage();
const errors = [];
page.on('console', m => { if (m.type() === 'error') errors.push('CONSOLE: ' + m.text()); });
page.on('pageerror', e => errors.push('PAGEERROR: ' + e.message));
await page.goto(url, { waitUntil: 'networkidle', timeout: 30000 }).catch(e => errors.push('GOTO: ' + e.message));
await page.waitForTimeout(2500);
const root = await page.$('#root');
const rootHTML = root ? (await root.innerHTML()).slice(0, 800) : '(no #root)';
const bodyText = (await page.textContent('body')).slice(0, 400);
console.log('=== ERRORS ===');
console.log(errors.length ? errors.join('\n') : '(none)');
console.log('=== #root innerHTML (first 800) ===');
console.log(rootHTML);
console.log('=== body text (first 400) ===');
console.log(bodyText);
await browser.close();
