import express from 'express';
import crypto from 'crypto';
import db from '../db.js';
import { requirePerm, logActivity } from '../auth.js';

const router = express.Router();
const I18N = { en:{joined:'Joined', eta:'ETA', surge:'Surge', voice:'Voice alert', think:'intake'}, hi:{joined:'शामिल', eta:'अनुमानित', surge:'भीड़', voice:'आवाज़ अलर्ट', think:'प्रवेश'}, ja:{joined:'受付', eta:'目安', surge:'混雑', voice:'音声通知', think:'受付中'} };
const DAY = 86_400_000;
const code = prefix => `${prefix}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`;
const isoDate = ts => new Date(ts).toISOString().slice(0, 10);
const dateStart = date => { const d = /^\d{4}-\d{2}-\d{2}$/.test(date || '') ? new Date(`${date}T00:00:00.000Z`) : new Date(); return Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate()); };
const actor = req => req.user?.username || req.user?.role || 'system';
const publicRequests = new Map();
function publicRateLimit(req, res, next) {
  const key = req.ip || req.socket?.remoteAddress || 'unknown', now = Date.now();
  const recent = (publicRequests.get(key) || []).filter(t => now - t < 60_000);
  if (recent.length >= Number(process.env.HOSPITAL_PUBLIC_RATE_LIMIT || 20)) return res.status(429).json({ error: 'Too many requests. Please wait a minute and try again.' });
  recent.push(now); publicRequests.set(key, recent); next();
}
function detectLocale(t) { if (/[぀-ヿ]/.test(t || '')) return 'ja'; if (/[ऀ-ॿ]/.test(t || '')) return 'hi'; return 'en'; }
function understand(t) { const l = (t || '').toLowerCase(), m = l.match(/name is ([a-z]+)|i am ([a-z]+)|मेरा नाम ([a-z]+)|नाम ([a-z]+)|名前は ([a-z]+)|わたしは ([a-z]+)/) || []; const raw = m[1] || m[2] || m[3] || m[4] || m[5] || m[6]; return { name: raw ? raw.charAt(0).toUpperCase() + raw.slice(1) : '', complaint: (l.match(/fever|pain|दर्द|बुखार|熱|head|सिर|chest|सीने|頭|胸/) || [])[0] || '' }; }
function event(id, type, from, to, who = 'system', note = '') { db.prepare('INSERT INTO hospital_queue_events (appointment_id,event_type,from_status,to_status,actor,note,created_at) VALUES (?,?,?,?,?,?,?)').run(id, type, from || null, to || null, who, note, Date.now()); }
async function deliverNotification(row, appointment) {
  if (process.env.HOSPITAL_NOTIFICATION_TRANSPORT === 'mock' || process.env.AGENT_TEST_MODE === '1') return 'mock';
  const webhook = process.env.HOSPITAL_NOTIFICATION_WEBHOOK;
  if (!webhook) throw new Error('No notification provider configured');
  const response = await fetch(webhook, { method: 'POST', headers: { 'Content-Type': 'application/json', ...(process.env.HOSPITAL_NOTIFICATION_TOKEN ? { Authorization: `Bearer ${process.env.HOSPITAL_NOTIFICATION_TOKEN}` } : {}) }, body: JSON.stringify({ channel: row.channel, kind: row.kind, body: row.body, to: row.channel === 'email' ? appointment.email : appointment.phone, bookingCode: appointment.booking_code }) });
  if (!response.ok) throw new Error(`Provider returned ${response.status}`);
  return 'delivered';
}
function notify(id, kind, body, preferredChannel = '') {
  const appointment = db.prepare('SELECT * FROM hospital_appointments WHERE id=?').get(id); if (!appointment) return;
  const channel = preferredChannel || (appointment.phone ? 'sms' : appointment.email ? 'email' : 'in_app');
  const inserted = db.prepare('INSERT INTO hospital_notifications (appointment_id,channel,kind,body,status,created_at) VALUES (?,?,?,?,?,?)').run(id, channel, kind, body, 'queued', Date.now());
  const row = db.prepare('SELECT * FROM hospital_notifications WHERE id=?').get(inserted.lastInsertRowid);
  deliverNotification(row, appointment).then(() => db.prepare("UPDATE hospital_notifications SET status='delivered' WHERE id=?").run(row.id)).catch(error => db.prepare("UPDATE hospital_notifications SET status=? WHERE id=?").run(`failed: ${String(error.message).slice(0,100)}`, row.id));
}

function seedScheduling() {
  if (process.env.HOSPITAL_DEMO_SEED !== '1' || db.prepare('SELECT COUNT(*) c FROM hospital_doctors').get().c) return;
  const now = Date.now(), addDepartment = db.prepare('INSERT OR IGNORE INTO hospital_departments (name,location,created_at) VALUES (?,?,?)');
  [['General OPD','Main OPD'],['Pediatrics','Children’s Wing'],['Cardiology','Heart Centre']].forEach(row => addDepartment.run(...row, now));
  const add = db.prepare('INSERT INTO hospital_doctors (name,specialty,location,department,department_id,room,default_duration_min,created_at) VALUES (?,?,?,?,?,?,?,?)');
  [['Dr. Asha Mehta','General Medicine','Main OPD','General OPD','Room 101',15],['Dr. Rohan Shah','Pediatrics','Children’s Wing','Pediatrics','Room 202',20],['Dr. Neha Iyer','Cardiology','Heart Centre','Cardiology','Room 305',20]].forEach(([name,specialty,location,department,room,duration]) => {
    const departmentId = db.prepare('SELECT id FROM hospital_departments WHERE name=?').get(department).id;
    const doctorId = add.run(name,specialty,location,department,departmentId,room,duration,now).lastInsertRowid;
    for (let weekday = 0; weekday < 7; weekday++) db.prepare('INSERT INTO hospital_slot_policies (doctor_id,weekday,start_time,end_time,duration_min,capacity,service_type,created_at) VALUES (?,?,?,?,?,?,?,?)').run(doctorId,weekday,'09:00','17:00',duration,1,'Consultation',now);
  });
}
function ensureSlots(date, doctorId) {
  const start = dateStart(date), doctors = doctorId ? db.prepare('SELECT * FROM hospital_doctors WHERE id=? AND active=1').all(doctorId) : db.prepare('SELECT * FROM hospital_doctors WHERE active=1').all();
  if (db.prepare('SELECT 1 FROM hospital_holidays WHERE holiday_date=?').get(isoDate(start))) return;
  const add = db.prepare('INSERT OR IGNORE INTO hospital_slots (doctor_id,starts_at,ends_at,capacity,reserved,status,service_type,created_at) VALUES (?,?,?,?,?,?,?,?)');
  const weekday = new Date(start).getUTCDay();
  for (const doctor of doctors) {
    const policies = db.prepare('SELECT * FROM hospital_slot_policies WHERE doctor_id=? AND weekday=? AND active=1 ORDER BY start_time').all(doctor.id, weekday);
    for (const policy of policies) {
      const [startHour, startMinute] = policy.start_time.split(':').map(Number), [endHour, endMinute] = policy.end_time.split(':').map(Number), first = startHour * 60 + startMinute, last = endHour * 60 + endMinute;
      for (let minute = first; minute + policy.duration_min <= last; minute += policy.duration_min) { const starts = start + minute * 60_000, ends = starts + policy.duration_min * 60_000; const blocked = db.prepare("SELECT 1 FROM hospital_schedule_blocks WHERE doctor_id=? AND starts_at<? AND ends_at>? LIMIT 1").get(doctor.id, ends, starts); if (!blocked) add.run(doctor.id, starts, ends, policy.capacity, 0, 'open', policy.service_type, Date.now()); }
    }
  }
}
function recomputeQueue(doctorId, date) {
  const start = dateStart(date), end = start + DAY;
  const rows = db.prepare("SELECT id FROM hospital_appointments WHERE doctor_id=? AND checked_in_at>=? AND checked_in_at<? AND status IN ('checked_in','called') ORDER BY CASE priority WHEN 'urgent' THEN 0 ELSE 1 END, checked_in_at,id").all(doctorId, start, end);
  const historical = db.prepare("SELECT AVG(completed_at-called_at)/60000 avg FROM hospital_appointments WHERE doctor_id=? AND completed_at IS NOT NULL AND called_at IS NOT NULL AND completed_at>called_at").get(doctorId).avg;
  const serviceMinutes = Math.max(5, Math.min(60, Math.round(historical || db.prepare('SELECT default_duration_min duration FROM hospital_doctors WHERE id=?').get(doctorId)?.duration || 12)));
  const update = db.prepare('UPDATE hospital_appointments SET queue_number=?,estimated_wait_min=?,updated_at=? WHERE id=?'); rows.forEach((row, i) => update.run(i + 1, i * serviceMinutes, Date.now(), row.id));
}
function appointmentRow(id) { return db.prepare('SELECT a.*,d.name doctor_name,d.specialty,d.location,d.room,s.starts_at,s.ends_at,s.service_type FROM hospital_appointments a JOIN hospital_doctors d ON d.id=a.doctor_id LEFT JOIN hospital_slots s ON s.id=a.slot_id WHERE a.id=?').get(id); }
function publicAppointment(a) { if (!a) return null; const { abha_number, consent_at, priority_reason, ...safe } = a; return safe; }
function bookingPreview(a) { return a ? { booking_code:a.booking_code,status:a.status,doctor_name:a.doctor_name,specialty:a.specialty,location:a.location,room:a.room,starts_at:a.starts_at,ends_at:a.ends_at,service_type:a.service_type } : null; }
function portalAccess(req, appointment) {
  const token = String(req.get('x-patient-token') || '');
  const digest = token ? crypto.createHash('sha256').update(token).digest('hex') : '';
  return !!token && !!db.prepare("SELECT 1 FROM hospital_public_tokens WHERE appointment_id=? AND purpose='portal' AND code=? AND verified_at IS NOT NULL AND expires_at>?").get(appointment.id, digest, Date.now());
}
function portalBundle(appointment) {
  const related = db.prepare("SELECT a.id,a.booking_code,a.status,a.consultation_mode,a.payment_status,d.name doctor_name,d.specialty,d.location,d.room,s.starts_at,s.ends_at FROM hospital_appointments a JOIN hospital_doctors d ON d.id=a.doctor_id LEFT JOIN hospital_slots s ON s.id=a.slot_id WHERE (a.phone<>'' AND a.phone=?) OR a.id=? ORDER BY COALESCE(s.starts_at,a.created_at) DESC LIMIT 20").all(appointment.phone || '__none__', appointment.id);
  return {
    appointment: publicAppointment(appointment),
    appointments: related,
    notifications: db.prepare('SELECT channel,kind,body,status,created_at FROM hospital_notifications WHERE appointment_id=? ORDER BY created_at DESC LIMIT 30').all(appointment.id),
    documents: db.prepare('SELECT id,name,document_type,status,created_at FROM hospital_patient_documents WHERE appointment_id=? ORDER BY created_at DESC').all(appointment.id),
    stages: ['checked_in','called','completed'].includes(appointment.status) ? visitStages(appointment.id) : []
  };
}
const TRIAGE_FLAGS = ['difficulty_breathing','chest_pain','severe_bleeding','loss_of_consciousness','stroke_signs','self_harm_risk'];
const VISIT_STAGES = [['registration','Registration'],['vitals','Vitals'],['consultation','Consultation'],['lab','Laboratory'],['pharmacy','Pharmacy'],['billing','Billing']];
function ensureVisitStages(appointmentId) { const add = db.prepare('INSERT OR IGNORE INTO hospital_visit_stages (appointment_id,stage,label,status,updated_at) VALUES (?,?,?,?,?)'); for (const [stage,label] of VISIT_STAGES) add.run(appointmentId,stage,label,['lab','pharmacy','billing'].includes(stage) ? 'not_required' : 'waiting',Date.now()); }
function visitStages(appointmentId) { ensureVisitStages(appointmentId); return db.prepare('SELECT * FROM hospital_visit_stages WHERE appointment_id=? ORDER BY id').all(appointmentId); }
function fhirAppointment(a) { return { resourceType:'Appointment', id:String(a.id), identifier:[{system:'urn:masystem:booking',value:a.booking_code}], status: ({confirmed:'booked',checked_in:'arrived',called:'arrived',completed:'fulfilled',cancelled:'cancelled',no_show:'noshow',waitlisted:'waitlist'})[a.status] || 'pending', serviceType:a.service_type ? [{text:a.service_type}] : undefined, specialty:[{text:a.specialty}], description:a.reason || undefined, start:a.starts_at ? new Date(a.starts_at).toISOString() : undefined, end:a.ends_at ? new Date(a.ends_at).toISOString() : undefined, participant:[{actor:{display:a.patient_name},status:'accepted'},{actor:{display:a.doctor_name},status:'accepted'},{actor:{display:a.room || a.location},status:'accepted'}] }; }
async function syncIntegration(appointment, target) { const webhook = target === 'abdm' ? process.env.HOSPITAL_ABDM_WEBHOOK : process.env.HOSPITAL_HMIS_WEBHOOK, token = target === 'abdm' ? process.env.HOSPITAL_ABDM_TOKEN : process.env.HOSPITAL_HMIS_TOKEN; if (!webhook) throw new Error(`${target.toUpperCase()} integration is not configured.`); const response = await fetch(webhook,{method:'POST',headers:{'Content-Type':'application/fhir+json',...(token ? {Authorization:`Bearer ${token}`} : {})},body:JSON.stringify(fhirAppointment(appointment))}); if (!response.ok) throw new Error(`${target.toUpperCase()} returned ${response.status}`); }
function rebookAffectedAppointments(absence) {
  const rows = db.prepare("SELECT a.*,s.starts_at FROM hospital_appointments a JOIN hospital_slots s ON s.id=a.slot_id WHERE a.doctor_id=? AND a.status='confirmed' AND s.starts_at>=? AND s.starts_at<?").all(absence.doctor_id,absence.starts_at,absence.ends_at); let transferred = 0, needsRebooking = 0;
  for (const a of rows) { let replacement = null; if (absence.substitute_doctor_id) { ensureSlots(isoDate(a.starts_at),absence.substitute_doctor_id); replacement = db.prepare("SELECT * FROM hospital_slots WHERE doctor_id=? AND starts_at>=? AND starts_at<? AND status='open' AND reserved<capacity ORDER BY starts_at LIMIT 1").get(absence.substitute_doctor_id,a.starts_at,dateStart(isoDate(a.starts_at))+DAY); }
    if (replacement) { db.prepare('UPDATE hospital_slots SET reserved=MAX(reserved-1,0) WHERE id=?').run(a.slot_id); db.prepare('UPDATE hospital_slots SET reserved=reserved+1 WHERE id=?').run(replacement.id); db.prepare('UPDATE hospital_appointments SET doctor_id=?,slot_id=?,original_doctor_id=COALESCE(original_doctor_id,?),updated_at=? WHERE id=?').run(absence.substitute_doctor_id,replacement.id,absence.doctor_id,Date.now(),a.id); event(a.id,'substitute_rebooked','confirmed','confirmed','system',`Doctor absence ${absence.id}`); notify(a.id,'rebooked_substitute','Your appointment has been moved to an available substitute doctor and time.'); transferred++; }
    else { db.prepare("UPDATE hospital_appointments SET status='rebooking_required',original_doctor_id=COALESCE(original_doctor_id,?),updated_at=? WHERE id=?").run(absence.doctor_id,Date.now(),a.id); db.prepare('UPDATE hospital_slots SET reserved=MAX(reserved-1,0) WHERE id=?').run(a.slot_id); event(a.id,'rebooking_required','confirmed','rebooking_required','system',`Doctor absence ${absence.id}`); notify(a.id,'rebooking_required','Your doctor is unavailable. Our team will contact you with new appointment options.'); needsRebooking++; }
  } return { affected:rows.length,transferred,needsRebooking };
}
function promoteWaitlist(slotId) {
  const waiting = db.prepare("SELECT a.* FROM hospital_waitlist w JOIN hospital_appointments a ON a.id=w.appointment_id WHERE w.active=1 AND a.slot_id=? AND a.status='waitlisted' ORDER BY w.created_at LIMIT 1").get(slotId);
  if (!waiting) return;
  const now = Date.now(); db.prepare("UPDATE hospital_waitlist SET active=0 WHERE appointment_id=?").run(waiting.id); db.prepare("UPDATE hospital_slots SET reserved=reserved+1 WHERE id=?").run(slotId); db.prepare("UPDATE hospital_appointments SET status='confirmed',updated_at=? WHERE id=?").run(now, waiting.id);
  event(waiting.id,'waitlist_promoted','waitlisted','confirmed','system'); notify(waiting.id,'waitlist_promoted','A slot is now available and your appointment is confirmed.');
}

async function intake(text, locale) {
  locale = locale || detectLocale(text); const L = I18N[locale] || I18N.en, p = understand(text), waiting = db.prepare("SELECT COUNT(*) c FROM hospital_queue WHERE status='waiting'").get().c + 1, eta = waiting * 7;
  const id = db.prepare('INSERT INTO hospital_queue (name,complaint,locale,channel,position,eta_min,status,created_at) VALUES (?,?,?,?,?,?,?,?)').run(p.name || 'Guest', p.complaint, locale, 'web', waiting, eta, 'waiting', Date.now()).lastInsertRowid;
  const steps = [{tool:'think',result:`(${L.think}) ${p.name || 'Guest'}`},{tool:'join',result:`${L.joined} #${id} (web)`},{tool:'report_position',result:`${waiting}/${waiting} · ${eta} ${L.eta}`}];
  if (waiting >= 5) steps.push({tool:'surge_detected',result:`${L.surge}: ${waiting}`},{tool:'notify_voice',result:`${L.voice} (${waiting})`}); return { id, steps, locale };
}

// Public booking: no patient lists or staff data are exposed.
router.use('/public', publicRateLimit);
router.get('/public/doctors', (_req,res) => { seedScheduling(); res.json(db.prepare('SELECT id,name,specialty,location,department,room,default_duration_min FROM hospital_doctors WHERE active=1 ORDER BY name').all()); });
router.get('/public/services', (_req,res) => { seedScheduling(); res.json({departments:db.prepare('SELECT id,name,location FROM hospital_departments WHERE active=1 ORDER BY name').all(),doctors:db.prepare('SELECT id,name,specialty,location,department,room FROM hospital_doctors WHERE active=1 ORDER BY department,name').all()}); });
router.get('/public/slots', (req,res) => { const doctorId = Number(req.query.doctorId), date = String(req.query.date || isoDate(Date.now())); if (!doctorId) return res.status(400).json({error:'doctorId required'}); if (dateStart(date) < dateStart(isoDate(Date.now()))) return res.status(400).json({error:'Choose today or a future date.'}); seedScheduling(); ensureSlots(date, doctorId); const start = dateStart(date); res.json(db.prepare("SELECT id,starts_at,ends_at,capacity,reserved,status,service_type,(capacity-reserved) available FROM hospital_slots WHERE doctor_id=? AND starts_at>=? AND starts_at<? AND status='open' ORDER BY starts_at").all(doctorId, start, start + DAY)); });
router.post('/public/bookings', (req,res) => {
  const b = req.body || {}, name = String(b.patientName || '').trim().slice(0,100), doctorId = Number(b.doctorId), slotId = Number(b.slotId); if (!name || !doctorId || !slotId) return res.status(400).json({error:'patient name, doctor, and slot are required'});
  try {
    const result = db.transaction(() => { const slot = db.prepare('SELECT * FROM hospital_slots WHERE id=? AND doctor_id=?').get(slotId, doctorId); if (!slot) throw new Error('Selected slot is no longer available.'); const now = Date.now(), status = slot.reserved < slot.capacity ? 'confirmed' : b.joinWaitlist ? 'waitlisted' : ''; if (!status) throw new Error('This slot is full. Join the waitlist or choose another time.'); const mode = ['in_person','video'].includes(b.consultationMode) ? b.consultationMode : 'in_person', telehealth = mode === 'video' ? `${process.env.HOSPITAL_TELEHEALTH_BASE_URL || 'https://video.example.invalid/visit'}/${code('ROOM')}` : ''; const id = db.prepare('INSERT INTO hospital_appointments (booking_code,checkin_code,patient_name,phone,email,abha_number,consent_at,doctor_id,slot_id,reason,status,preferred_channel,caregiver_name,caregiver_phone,accessibility_needs,insurance_provider,insurance_member_id,consultation_mode,language,telehealth_url,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(code('APT'), code('CHK'), name, String(b.phone || '').slice(0,40), String(b.email || '').slice(0,254), String(b.abhaNumber || '').slice(0,30), b.consent ? now : null, doctorId, slotId, String(b.reason || '').slice(0,500), status, ['sms','email','whatsapp'].includes(b.preferredChannel) ? b.preferredChannel : 'sms', String(b.caregiverName || '').slice(0,100), String(b.caregiverPhone || '').slice(0,40), String(b.accessibilityNeeds || '').slice(0,500), String(b.insuranceProvider || '').slice(0,100), String(b.insuranceMemberId || '').slice(0,100), mode, String(b.language || 'en').slice(0,10), telehealth, now, now).lastInsertRowid; if (status === 'confirmed') db.prepare('UPDATE hospital_slots SET reserved=reserved+1 WHERE id=?').run(slotId); else db.prepare('INSERT INTO hospital_waitlist (appointment_id,requested_date,created_at) VALUES (?,?,?)').run(id, isoDate(slot.starts_at), now); event(id,status === 'confirmed' ? 'booked':'waitlisted',null,status,'patient'); notify(id,status === 'confirmed' ? 'booking_confirmation':'waitlist_confirmation',status === 'confirmed' ? 'Your appointment is confirmed.':'You are on the waitlist.', ['sms','email'].includes(b.preferredChannel) ? b.preferredChannel : ''); return appointmentRow(id); })();
    res.status(201).json({appointment:publicAppointment(result),checkinUrl:`/hospital/check-in?code=${result.checkin_code}`,manageUrl:`/hospital/visit?code=${result.booking_code}`});
  } catch (error) { res.status(409).json({error:error.message}); }
});
router.get('/public/bookings/:code', (req,res) => { const a = appointmentRowByBooking(req.params.code); if (!a) return res.status(404).json({error:'Booking not found.'}); res.json({appointment:bookingPreview(a),verificationRequired:true}); });
function appointmentRowByBooking(bookingCode) { return db.prepare('SELECT a.*,d.name doctor_name,d.specialty,d.location,d.room,s.starts_at,s.ends_at,s.service_type FROM hospital_appointments a JOIN hospital_doctors d ON d.id=a.doctor_id LEFT JOIN hospital_slots s ON s.id=a.slot_id WHERE a.booking_code=?').get(bookingCode); }
router.post('/public/bookings/:code/send-verification', (req,res) => {
  const a = appointmentRowByBooking(req.params.code); if (!a || (!a.phone && !a.email)) return res.status(404).json({error:'A booking with a phone or email is required.'});
  const otp = process.env.AGENT_TEST_MODE === '1' ? String(process.env.HOSPITAL_TEST_OTP || '123456') : String(Math.floor(100000 + Math.random() * 900000)), now = Date.now();
  db.prepare("UPDATE hospital_public_tokens SET expires_at=? WHERE appointment_id=? AND purpose='manage' AND verified_at IS NULL").run(now, a.id);
  db.prepare('INSERT INTO hospital_public_tokens (appointment_id,purpose,code,expires_at,created_at) VALUES (?,?,?,?,?)').run(a.id,'manage',otp,now + 10 * 60_000,now);
  notify(a.id,'verification_code',`Your MASystem Hospital verification code is ${otp}. It expires in 10 minutes.`);
  res.json({ok:true,delivery: process.env.HOSPITAL_NOTIFICATION_TRANSPORT === 'mock' || process.env.AGENT_TEST_MODE === '1' ? 'mock' : 'queued',...(process.env.AGENT_TEST_MODE === '1' ? {testCode:otp} : {})});
});
router.post('/public/bookings/:code/verify', (req,res) => { const a = appointmentRowByBooking(req.params.code), otp = String(req.body?.code || ''); if (!a) return res.status(404).json({error:'Booking not found.'}); const token = db.prepare("SELECT * FROM hospital_public_tokens WHERE appointment_id=? AND purpose='manage' AND code=? AND expires_at>? ORDER BY id DESC LIMIT 1").get(a.id,otp,Date.now()); if (!token) return res.status(400).json({error:'Invalid or expired verification code.'}); const now = Date.now(), session = crypto.randomBytes(24).toString('hex'), digest = crypto.createHash('sha256').update(session).digest('hex'); db.prepare('UPDATE hospital_public_tokens SET verified_at=? WHERE id=?').run(now,token.id); db.prepare("UPDATE hospital_public_tokens SET expires_at=? WHERE appointment_id=? AND purpose='portal'").run(now,a.id); db.prepare('INSERT INTO hospital_public_tokens (appointment_id,purpose,code,expires_at,verified_at,created_at) VALUES (?,?,?,?,?,?)').run(a.id,'portal',digest,now + 30 * 60_000,now,now); res.json({ok:true,patientToken:session,expiresIn:1800}); });
router.get('/public/portal/:code', (req,res) => { const a = appointmentRowByBooking(req.params.code); if (!a || !portalAccess(req,a)) return res.status(401).json({error:'Verify your booking to continue.'}); res.json(portalBundle(a)); });
router.patch('/public/portal/:code/preferences', (req,res) => { const a = appointmentRowByBooking(req.params.code); if (!a || !portalAccess(req,a)) return res.status(401).json({error:'Verify your booking to continue.'}); const b=req.body||{}, channel=['sms','email','whatsapp'].includes(b.preferredChannel)?b.preferredChannel:a.preferred_channel, language=String(b.language||a.language).slice(0,10); db.prepare('UPDATE hospital_appointments SET preferred_channel=?,language=?,caregiver_name=?,caregiver_phone=?,accessibility_needs=?,updated_at=? WHERE id=?').run(channel,language,String(b.caregiverName??a.caregiver_name).slice(0,100),String(b.caregiverPhone??a.caregiver_phone).slice(0,40),String(b.accessibilityNeeds??a.accessibility_needs).slice(0,500),Date.now(),a.id); event(a.id,'preferences_updated',a.preferred_channel,channel,'patient'); res.json(portalBundle(appointmentRow(a.id))); });
router.post('/public/portal/:code/previsit', (req,res) => { const a=appointmentRowByBooking(req.params.code); if(!a||!portalAccess(req,a)) return res.status(401).json({error:'Verify your booking to continue.'}); const answers={medications:String(req.body?.medications||'').slice(0,1000),allergies:String(req.body?.allergies||'').slice(0,1000),notes:String(req.body?.notes||'').slice(0,1000)}; db.prepare('UPDATE hospital_appointments SET previsit_answers=?,updated_at=? WHERE id=?').run(JSON.stringify(answers),Date.now(),a.id); event(a.id,'previsit_completed',null,'completed','patient'); notify(a.id,'previsit_received','Your pre-visit information was received.'); res.json({ok:true,answers}); });
router.post('/public/portal/:code/documents', (req,res) => { const a=appointmentRowByBooking(req.params.code); if(!a||!portalAccess(req,a)) return res.status(401).json({error:'Verify your booking to continue.'}); const name=String(req.body?.name||'').trim().slice(0,150), type=String(req.body?.documentType||'other').slice(0,50); if(!name)return res.status(400).json({error:'Document name is required.'}); const id=db.prepare('INSERT INTO hospital_patient_documents (appointment_id,name,document_type,created_at) VALUES (?,?,?,?)').run(a.id,name,type,Date.now()).lastInsertRowid; event(a.id,'document_received',null,'received','patient',type); res.status(201).json({document:db.prepare('SELECT id,name,document_type,status,created_at FROM hospital_patient_documents WHERE id=?').get(id)}); });
router.post('/public/portal/:code/payment-intent', (req,res) => { const a=appointmentRowByBooking(req.params.code); if(!a||!portalAccess(req,a)) return res.status(401).json({error:'Verify your booking to continue.'}); if(!process.env.HOSPITAL_PAYMENT_WEBHOOK){db.prepare("UPDATE hospital_appointments SET payment_status='provider_required',updated_at=? WHERE id=?").run(Date.now(),a.id);return res.json({status:'provider_required',message:'Secure payment will be enabled after the hospital connects its approved payment provider.'});} res.json({status:'redirect_required',paymentUrl:process.env.HOSPITAL_PAYMENT_WEBHOOK}); });
router.post('/public/portal/:code/cancel', (req,res) => { const a=appointmentRowByBooking(req.params.code); if(!a||!portalAccess(req,a))return res.status(401).json({error:'Verify your booking to continue.'}); if(!['confirmed','waitlisted'].includes(a.status))return res.status(409).json({error:'This appointment can no longer be cancelled online.'}); const reason=String(req.body?.reason||'Patient requested').slice(0,300),now=Date.now(); db.prepare("UPDATE hospital_appointments SET status='cancelled',cancellation_reason=?,cancelled_at=?,updated_at=? WHERE id=?").run(reason,now,now,a.id); if(a.status==='confirmed'&&a.slot_id){db.prepare('UPDATE hospital_slots SET reserved=MAX(reserved-1,0) WHERE id=?').run(a.slot_id);promoteWaitlist(a.slot_id);} event(a.id,'cancelled',a.status,'cancelled','patient',reason);notify(a.id,'cancellation','Your booking was cancelled.');res.json(portalBundle(appointmentRow(a.id))); });
router.post('/public/portal/:code/reschedule', (req,res) => { const a=appointmentRowByBooking(req.params.code); if(!a||!portalAccess(req,a))return res.status(401).json({error:'Verify your booking to continue.'}); const doctorId=Number(req.body?.doctorId),slotId=Number(req.body?.slotId);if(a.status!=='confirmed'||!doctorId||!slotId)return res.status(400).json({error:'A confirmed appointment, doctor and slot are required.'});try{const updated=db.transaction(()=>{const slot=db.prepare('SELECT * FROM hospital_slots WHERE id=? AND doctor_id=?').get(slotId,doctorId);if(!slot||slot.reserved>=slot.capacity)throw new Error('Selected slot is not available.');db.prepare('UPDATE hospital_slots SET reserved=MAX(reserved-1,0) WHERE id=?').run(a.slot_id);db.prepare('UPDATE hospital_slots SET reserved=reserved+1 WHERE id=?').run(slotId);db.prepare('UPDATE hospital_appointments SET doctor_id=?,slot_id=?,updated_at=? WHERE id=?').run(doctorId,slotId,Date.now(),a.id);event(a.id,'rescheduled','confirmed','confirmed','patient');notify(a.id,'rescheduled','Your appointment time was updated.');promoteWaitlist(a.slot_id);return appointmentRow(a.id);})();res.json(portalBundle(updated));}catch(error){res.status(409).json({error:error.message});} });
router.post('/public/walk-ins', (req,res) => {
  const b = req.body || {}, doctorId = Number(b.doctorId), patientName = String(b.patientName || '').trim().slice(0,100); if (!patientName || !doctorId || !db.prepare('SELECT id FROM hospital_doctors WHERE id=? AND active=1').get(doctorId)) return res.status(400).json({error:'Patient name and active doctor are required.'});
  const now = Date.now(), id = db.prepare("INSERT INTO hospital_appointments (booking_code,checkin_code,patient_name,phone,email,doctor_id,reason,status,visit_type,language,checked_in_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)").run(code('WALK'),code('CHK'),patientName,String(b.phone || '').slice(0,40),'',doctorId,String(b.reason || '').slice(0,500),'checked_in','walk_in',String(b.language || 'en').slice(0,10),now,now,now).lastInsertRowid;
  event(id,'walk_in',null,'checked_in','kiosk'); recomputeQueue(doctorId,isoDate(now)); const a = appointmentRow(id); notify(id,'queue_token',`You are checked in. Queue number ${a.queue_number}; estimated wait ${a.estimated_wait_min} minutes.`); res.status(201).json({appointment:publicAppointment(a)});
});
router.get('/public/display', (req,res) => { const doctorId = Number(req.query.doctorId), date = String(req.query.date || isoDate(Date.now())); if (!doctorId) return res.status(400).json({error:'doctorId required'}); recomputeQueue(doctorId,date); const start = dateStart(date), doctor = db.prepare('SELECT name,specialty,location,room FROM hospital_doctors WHERE id=?').get(doctorId); if (!doctor) return res.status(404).json({error:'Doctor not found.'}); const queue = db.prepare("SELECT queue_number,status,estimated_wait_min,visit_type FROM hospital_appointments WHERE doctor_id=? AND checked_in_at>=? AND checked_in_at<? AND status IN ('checked_in','called') ORDER BY queue_number").all(doctorId,start,start+DAY); res.json({doctor,queue,updatedAt:Date.now()}); });
router.post('/public/bookings/:code/check-in', (req,res) => { const a = db.prepare('SELECT * FROM hospital_appointments WHERE checkin_code=?').get(req.params.code); if (!a) return res.status(404).json({error:'Check-in code not found.'}); if (a.status !== 'confirmed') return res.status(409).json({error:`This booking cannot check in (${a.status}).`}); const now = Date.now(); db.prepare("UPDATE hospital_appointments SET status='checked_in',checked_in_at=?,updated_at=? WHERE id=?").run(now,now,a.id); ensureVisitStages(a.id); db.prepare("UPDATE hospital_visit_stages SET status='completed',completed_at=?,updated_at=? WHERE appointment_id=? AND stage='registration'").run(now,now,a.id); event(a.id,'checked_in','confirmed','checked_in','patient'); recomputeQueue(a.doctor_id,isoDate(now)); const updated = appointmentRow(a.id); notify(a.id,'queue_token',`Queue number ${updated.queue_number}; estimated wait ${updated.estimated_wait_min} minutes.`); res.json({appointment:publicAppointment(updated)}); });
router.post('/public/bookings/:code/cancel', (req,res) => { const a = appointmentRowByBooking(req.params.code); if (!a || !portalAccess(req,a)) return res.status(401).json({error:'Verify your booking to continue.'}); res.status(410).json({error:'Use the secure patient portal cancellation workflow.'}); });
router.post('/public/bookings/:code/reschedule', (req,res) => { const a = appointmentRowByBooking(req.params.code); if (!a || !portalAccess(req,a)) return res.status(401).json({error:'Verify your booking to continue.'}); res.status(410).json({error:'Use the secure patient portal rescheduling workflow.'}); });
router.post('/demo', (req,res) => { const text = String(req.body?.text || '').trim().slice(0,500); if (!text) return res.status(400).json({error:'Please describe the patient request.'}); const locale = detectLocale(text), L = I18N[locale] || I18N.en, p = understand(text); res.json({demo:true,locale,steps:[{tool:'demo_intake',result:`(${L.think}) ${p.name || 'Demo patient'}`},{tool:'simulated_token',result:`${L.joined} · demo token #A-104`},{tool:'estimated_wait',result:`3 ${locale === 'hi' ? 'मिनट' : locale === 'ja' ? '分' : 'min'} ${L.eta}`}]}); });

// Legacy chat plus staff-facing operational controls.
router.post('/intake', requirePerm('hospital:chat'), async (req,res) => { const output = await intake(req.body?.text || '',req.body?.locale); logActivity('hospital','🏥','Patient intake',String(req.body?.text || '').slice(0,40)); res.json(output); });
router.get('/state', requirePerm('hospital:manage'), (_req,res) => { const queue = db.prepare("SELECT * FROM hospital_queue WHERE status='waiting' ORDER BY position").all(); res.json({queue,waiting:queue.length}); });
router.post('/next', requirePerm('hospital:manage'), (_req,res) => { const row = db.prepare("SELECT * FROM hospital_queue WHERE status='waiting' ORDER BY position LIMIT 1").get(); if (!row) return res.json({msg:'empty'}); db.prepare("UPDATE hospital_queue SET status='seen' WHERE id=?").run(row.id); res.json({called:row}); });
router.get('/departments', requirePerm('hospital:manage'), (_req,res) => res.json(db.prepare('SELECT * FROM hospital_departments WHERE active=1 ORDER BY name').all()));
router.post('/departments', requirePerm('hospital:manage'), (req,res) => { const b = req.body || {}, name = String(b.name || '').trim().slice(0,100); if (!name) return res.status(400).json({error:'Department name is required.'}); try { const id = db.prepare('INSERT INTO hospital_departments (name,location,created_at) VALUES (?,?,?)').run(name,String(b.location || 'Main campus').slice(0,100),Date.now()).lastInsertRowid; res.status(201).json({department:db.prepare('SELECT * FROM hospital_departments WHERE id=?').get(id)}); } catch { res.status(409).json({error:'A department with this name already exists.'}); } });
router.delete('/departments/:id', requirePerm('hospital:manage'), (req,res) => { const id = Number(req.params.id); if (db.prepare('SELECT 1 FROM hospital_doctors WHERE department_id=? LIMIT 1').get(id)) return res.status(409).json({error:'Move or deactivate doctors before removing this department.'}); db.prepare('DELETE FROM hospital_departments WHERE id=?').run(id); res.json({ok:true}); });
router.get('/holidays', requirePerm('hospital:manage'), (_req,res) => res.json(db.prepare('SELECT * FROM hospital_holidays ORDER BY holiday_date').all()));
router.post('/holidays', requirePerm('hospital:manage'), (req,res) => { const b = req.body || {}, holidayDate = String(b.date || ''); if (!/^\d{4}-\d{2}-\d{2}$/.test(holidayDate) || !String(b.name || '').trim()) return res.status(400).json({error:'Holiday date and name are required.'}); try { const id = db.prepare('INSERT INTO hospital_holidays (holiday_date,name,created_at) VALUES (?,?,?)').run(holidayDate,String(b.name).trim().slice(0,100),Date.now()).lastInsertRowid; db.prepare("UPDATE hospital_slots SET status='blocked' WHERE starts_at>=? AND starts_at<?").run(dateStart(holidayDate),dateStart(holidayDate)+DAY); res.status(201).json({holiday:db.prepare('SELECT * FROM hospital_holidays WHERE id=?').get(id)}); } catch { res.status(409).json({error:'This holiday date is already configured.'}); } });
router.delete('/holidays/:id', requirePerm('hospital:manage'), (req,res) => { const holiday = db.prepare('SELECT * FROM hospital_holidays WHERE id=?').get(req.params.id); if (!holiday) return res.status(404).json({error:'Holiday not found.'}); db.prepare('DELETE FROM hospital_holidays WHERE id=?').run(holiday.id); db.prepare("UPDATE hospital_slots SET status='open' WHERE starts_at>=? AND starts_at<? AND reserved<capacity").run(dateStart(holiday.holiday_date),dateStart(holiday.holiday_date)+DAY); res.json({ok:true}); });
router.get('/slot-policies', requirePerm('hospital:manage'), (req,res) => { const doctorId = Number(req.query.doctorId || 0); res.json(db.prepare('SELECT p.*,d.name doctor_name FROM hospital_slot_policies p JOIN hospital_doctors d ON d.id=p.doctor_id WHERE (?=0 OR p.doctor_id=?) ORDER BY p.weekday,p.start_time').all(doctorId,doctorId)); });
router.post('/slot-policies', requirePerm('hospital:manage'), (req,res) => {
  const b = req.body || {}, doctorId = Number(b.doctorId), weekday = Number(b.weekday), duration = Math.max(5, Math.min(120, Number(b.durationMin))), capacity = Math.max(1, Math.min(20, Number(b.capacity) || 1)), startTime = String(b.startTime || ''), endTime = String(b.endTime || '');
  if (!db.prepare('SELECT 1 FROM hospital_doctors WHERE id=? AND active=1').get(doctorId) || !Number.isInteger(weekday) || weekday < 0 || weekday > 6 || !/^\d{2}:\d{2}$/.test(startTime) || !/^\d{2}:\d{2}$/.test(endTime) || !duration || startTime >= endTime) return res.status(400).json({error:'Doctor, weekday, valid time range, duration, and capacity are required.'});
  const id = db.prepare('INSERT INTO hospital_slot_policies (doctor_id,weekday,start_time,end_time,duration_min,capacity,service_type,created_at) VALUES (?,?,?,?,?,?,?,?)').run(doctorId,weekday,startTime,endTime,duration,capacity,String(b.serviceType || 'Consultation').slice(0,100),Date.now()).lastInsertRowid;
  res.status(201).json({policy:db.prepare('SELECT * FROM hospital_slot_policies WHERE id=?').get(id)});
});
router.delete('/slot-policies/:id', requirePerm('hospital:manage'), (req,res) => { const policy = db.prepare('SELECT * FROM hospital_slot_policies WHERE id=?').get(req.params.id); if (!policy) return res.status(404).json({error:'Slot policy not found.'}); db.prepare('DELETE FROM hospital_slot_policies WHERE id=?').run(policy.id); res.json({ok:true}); });
router.get('/doctors', requirePerm('hospital:manage'), (_req,res) => { seedScheduling(); res.json(db.prepare('SELECT * FROM hospital_doctors WHERE active=1 ORDER BY name').all()); });
router.post('/doctors', requirePerm('hospital:manage'), (req,res) => { const b = req.body || {}, name = String(b.name || '').trim().slice(0,100), specialty = String(b.specialty || '').trim().slice(0,100), departmentId = Number(b.departmentId); const department = db.prepare('SELECT * FROM hospital_departments WHERE id=? AND active=1').get(departmentId); if (!name || !specialty || !department) return res.status(400).json({error:'Doctor name, specialty, and an active department are required.'}); const id = db.prepare('INSERT INTO hospital_doctors (name,specialty,location,department,department_id,room,default_duration_min,created_at) VALUES (?,?,?,?,?,?,?,?)').run(name,specialty,department.location,department.name,department.id,String(b.room || 'Room to assign').slice(0,50),Math.max(5,Math.min(90,Number(b.duration) || 15)),Date.now()).lastInsertRowid; res.status(201).json({doctor:db.prepare('SELECT * FROM hospital_doctors WHERE id=?').get(id)}); });
router.patch('/doctors/:id', requirePerm('hospital:manage'), (req,res) => { const b = req.body || {}, id = Number(req.params.id), doctor = db.prepare('SELECT * FROM hospital_doctors WHERE id=?').get(id), department = b.departmentId ? db.prepare('SELECT * FROM hospital_departments WHERE id=? AND active=1').get(Number(b.departmentId)) : null; if (!doctor || (b.departmentId && !department)) return res.status(404).json({error:'Doctor or department not found.'}); db.prepare('UPDATE hospital_doctors SET location=?,department=?,department_id=?,room=?,default_duration_min=?,active=? WHERE id=?').run(String(department?.location ?? b.location ?? doctor.location).slice(0,100),String(department?.name ?? doctor.department).slice(0,100),department?.id ?? doctor.department_id,String(b.room ?? doctor.room).slice(0,50),Math.max(5,Math.min(90,Number(b.duration ?? doctor.default_duration_min))),b.active === false ? 0 : 1,id); res.json({doctor:db.prepare('SELECT * FROM hospital_doctors WHERE id=?').get(id)}); });
router.get('/triage/templates', requirePerm('hospital:manage'), (_req,res) => res.json({redFlags:TRIAGE_FLAGS,dispositions:['standard','nurse_review','emergency_escalation'],notice:'This is a staff assessment aid, not a diagnostic tool. Follow your hospital emergency policy.'}));
router.get('/appointments/:id/triage', requirePerm('hospital:manage'), (req,res) => res.json(db.prepare('SELECT * FROM hospital_triage_assessments WHERE appointment_id=? ORDER BY created_at DESC').all(req.params.id)));
router.post('/appointments/:id/triage', requirePerm('hospital:manage'), (req,res) => { const a = db.prepare('SELECT * FROM hospital_appointments WHERE id=?').get(req.params.id), b = req.body || {}, disposition = String(b.disposition || ''), flags = Array.isArray(b.redFlags) ? b.redFlags.filter(flag => TRIAGE_FLAGS.includes(flag)) : [], notes = String(b.notes || '').trim().slice(0,1000); if (!a || !['standard','nurse_review','emergency_escalation'].includes(disposition) || (flags.length && disposition === 'standard') || (disposition === 'emergency_escalation' && !notes)) return res.status(400).json({error:'Appointment and a valid nurse disposition are required. Red flags require nurse review or emergency escalation; escalation also requires a note.'}); const now = Date.now(); const id = db.prepare('INSERT INTO hospital_triage_assessments (appointment_id,disposition,red_flags,notes,nurse,created_at) VALUES (?,?,?,?,?,?)').run(a.id,disposition,JSON.stringify(flags),notes,actor(req),now).lastInsertRowid; db.prepare('UPDATE hospital_appointments SET triage_status=?,updated_at=? WHERE id=?').run(disposition,now,a.id); event(a.id,'triage_assessed',a.triage_status,disposition,actor(req),flags.join(',') || notes); if (disposition === 'emergency_escalation') notify(a.id,'emergency_escalation','Your case has been escalated to the clinical team. Please follow staff instructions.'); res.status(201).json({assessment:db.prepare('SELECT * FROM hospital_triage_assessments WHERE id=?').get(id)}); });
router.get('/appointments/:id/visit-stages', requirePerm('hospital:manage'), (req,res) => { if (!db.prepare('SELECT 1 FROM hospital_appointments WHERE id=?').get(req.params.id)) return res.status(404).json({error:'Appointment not found.'}); res.json({stages:visitStages(Number(req.params.id))}); });
router.post('/appointments/:id/visit-stages/:stage', requirePerm('hospital:manage'), (req,res) => { const appointmentId = Number(req.params.id), stage = req.params.stage, action = req.body?.action, row = visitStages(appointmentId).find(item => item.stage === stage); if (!row || !['start','complete','require','skip'].includes(action)) return res.status(400).json({error:'Valid stage and action are required.'}); const now = Date.now(); if (action === 'require') db.prepare("UPDATE hospital_visit_stages SET status='waiting',updated_at=? WHERE id=?").run(now,row.id); else if (action === 'start') db.prepare("UPDATE hospital_visit_stages SET status='in_progress',started_at=COALESCE(started_at,?),updated_at=? WHERE id=?").run(now,now,row.id); else db.prepare('UPDATE hospital_visit_stages SET status=?,completed_at=?,updated_at=? WHERE id=?').run(action === 'complete' ? 'completed' : 'skipped',now,now,row.id); event(appointmentId,`stage_${action}`,row.status,action,actor(req),stage); res.json({stages:visitStages(appointmentId)}); });
router.get('/doctor-absences', requirePerm('hospital:manage'), (_req,res) => res.json(db.prepare('SELECT a.*,d.name doctor_name,s.name substitute_name FROM hospital_doctor_absences a JOIN hospital_doctors d ON d.id=a.doctor_id LEFT JOIN hospital_doctors s ON s.id=a.substitute_doctor_id ORDER BY a.starts_at DESC').all()));
router.post('/doctor-absences', requirePerm('hospital:manage'), (req,res) => { const b = req.body || {}, doctorId = Number(b.doctorId), substituteId = b.substituteDoctorId ? Number(b.substituteDoctorId) : null, starts = Number(b.startsAt), ends = Number(b.endsAt); if (!db.prepare('SELECT 1 FROM hospital_doctors WHERE id=? AND active=1').get(doctorId) || (substituteId && (!db.prepare('SELECT 1 FROM hospital_doctors WHERE id=? AND active=1').get(substituteId) || substituteId === doctorId)) || !starts || !ends || ends <= starts) return res.status(400).json({error:'Doctor, valid absence period, and a different active substitute (if supplied) are required.'}); const id = db.prepare('INSERT INTO hospital_doctor_absences (doctor_id,starts_at,ends_at,substitute_doctor_id,reason,created_by,created_at) VALUES (?,?,?,?,?,?,?)').run(doctorId,starts,ends,substituteId,String(b.reason || '').slice(0,300),actor(req),Date.now()).lastInsertRowid; const result = rebookAffectedAppointments(db.prepare('SELECT * FROM hospital_doctor_absences WHERE id=?').get(id)); res.status(201).json({absence:db.prepare('SELECT * FROM hospital_doctor_absences WHERE id=?').get(id),...result}); });
router.get('/integrations/status', requirePerm('hospital:manage'), (_req,res) => res.json({hmis:{configured:!!process.env.HOSPITAL_HMIS_WEBHOOK},abdm:{configured:!!process.env.HOSPITAL_ABDM_WEBHOOK,requiresOnboarding:true},fhirVersion:'R4 Appointment'}));
router.get('/appointments/:id/fhir', requirePerm('hospital:manage'), (req,res) => { const a = appointmentRow(req.params.id); if (!a) return res.status(404).json({error:'Appointment not found.'}); res.type('application/fhir+json').json(fhirAppointment(a)); });
router.post('/appointments/:id/sync', requirePerm('hospital:manage'), async (req,res) => { const a = appointmentRow(req.params.id), target = String(req.body?.target || ''); if (!a || !['hmis','abdm'].includes(target)) return res.status(400).json({error:'Appointment and integration target are required.'}); const now = Date.now(); try { await syncIntegration(a,target); db.prepare('INSERT INTO hospital_integration_events (appointment_id,target,event_type,status,detail,created_at) VALUES (?,?,?,?,?,?)').run(a.id,target,'appointment_upsert','delivered','Provider accepted FHIR Appointment',now); res.json({ok:true,target}); } catch (error) { db.prepare('INSERT INTO hospital_integration_events (appointment_id,target,event_type,status,detail,created_at) VALUES (?,?,?,?,?,?)').run(a.id,target,'appointment_upsert','not_configured',String(error.message).slice(0,300),now); res.status(409).json({error:error.message}); } });
router.get('/schedule-blocks', requirePerm('hospital:manage'), (req,res) => { const doctorId = Number(req.query.doctorId || 0), start = dateStart(String(req.query.date || isoDate(Date.now()))); res.json(db.prepare('SELECT * FROM hospital_schedule_blocks WHERE (?=0 OR doctor_id=?) AND starts_at<? AND ends_at>? ORDER BY starts_at').all(doctorId,doctorId,start + DAY,start)); });
router.post('/schedule-blocks', requirePerm('hospital:manage'), (req,res) => { const b = req.body || {}, doctorId = Number(b.doctorId), starts = Number(b.startsAt), ends = Number(b.endsAt); if (!doctorId || !starts || !ends || ends <= starts) return res.status(400).json({error:'Doctor and valid start/end times are required.'}); const id = db.prepare('INSERT INTO hospital_schedule_blocks (doctor_id,starts_at,ends_at,kind,reason,created_at) VALUES (?,?,?,?,?,?)').run(doctorId,starts,ends,String(b.kind || 'unavailable').slice(0,30),String(b.reason || '').slice(0,300),Date.now()).lastInsertRowid; db.prepare("UPDATE hospital_slots SET status='blocked' WHERE doctor_id=? AND starts_at<? AND ends_at>?").run(doctorId,ends,starts); res.status(201).json({block:db.prepare('SELECT * FROM hospital_schedule_blocks WHERE id=?').get(id)}); });
router.delete('/schedule-blocks/:id', requirePerm('hospital:manage'), (req,res) => { const block = db.prepare('SELECT * FROM hospital_schedule_blocks WHERE id=?').get(req.params.id); if (!block) return res.status(404).json({error:'Schedule block not found.'}); db.prepare('DELETE FROM hospital_schedule_blocks WHERE id=?').run(block.id); db.prepare("UPDATE hospital_slots SET status='open' WHERE doctor_id=? AND starts_at<? AND ends_at>? AND reserved<capacity").run(block.doctor_id,block.ends_at,block.starts_at); res.json({ok:true}); });
router.get('/appointments', requirePerm('hospital:manage'), (req,res) => { const date = String(req.query.date || isoDate(Date.now())), doctorId = Number(req.query.doctorId || 0), start = dateStart(date); res.json(db.prepare("SELECT a.*,d.name doctor_name,d.specialty,s.starts_at FROM hospital_appointments a JOIN hospital_doctors d ON d.id=a.doctor_id LEFT JOIN hospital_slots s ON s.id=a.slot_id WHERE (?=0 OR a.doctor_id=?) AND ((s.starts_at>=? AND s.starts_at<?) OR date(a.created_at/1000,'unixepoch')=?) ORDER BY s.starts_at,a.created_at").all(doctorId,doctorId,start,start+DAY,date)); });
router.get('/queue', requirePerm('hospital:manage'), (req,res) => { const doctorId = Number(req.query.doctorId), date = String(req.query.date || isoDate(Date.now())); if (!doctorId) return res.status(400).json({error:'doctorId required'}); recomputeQueue(doctorId,date); const start = dateStart(date); res.json(db.prepare("SELECT a.*,d.name doctor_name FROM hospital_appointments a JOIN hospital_doctors d ON d.id=a.doctor_id WHERE a.doctor_id=? AND a.checked_in_at>=? AND a.checked_in_at<? AND a.status IN ('checked_in','called') ORDER BY a.queue_number").all(doctorId,start,start+DAY)); });
router.get('/metrics', requirePerm('hospital:manage'), (req,res) => { const date = String(req.query.date || isoDate(Date.now())), start = dateStart(date), end = start + DAY, count = status => db.prepare('SELECT COUNT(*) c FROM hospital_appointments WHERE created_at>=? AND created_at<? AND status=?').get(start,end,status).c, wait = db.prepare("SELECT AVG(CASE WHEN called_at IS NOT NULL THEN (called_at-checked_in_at)/60000 ELSE estimated_wait_min END) avg FROM hospital_appointments WHERE checked_in_at>=? AND checked_in_at<?").get(start,end).avg || 0, service = db.prepare("SELECT AVG((completed_at-called_at)/60000) avg FROM hospital_appointments WHERE completed_at>=? AND completed_at<? AND called_at IS NOT NULL").get(start,end).avg || 0, total = db.prepare('SELECT COUNT(*) c FROM hospital_appointments WHERE created_at>=? AND created_at<?').get(start,end).c; res.json({total,booked:count('confirmed'),checkedIn:count('checked_in'),called:count('called'),completed:count('completed'),cancelled:count('cancelled'),noShow:count('no_show'),waitlisted:count('waitlisted'),averageWaitMin:Math.round(wait),averageServiceMin:Math.round(service),noShowRate: total ? Math.round(count('no_show') * 100 / total) : 0}); });
router.get('/notifications', requirePerm('hospital:manage'), (req,res) => { const id = Number(req.query.appointmentId || 0); res.json(db.prepare('SELECT n.*,a.patient_name FROM hospital_notifications n JOIN hospital_appointments a ON a.id=n.appointment_id WHERE (?=0 OR n.appointment_id=?) ORDER BY n.created_at DESC LIMIT 100').all(id,id)); });
router.post('/appointments/:id/check-in', requirePerm('hospital:manage'), (req,res) => { const a = db.prepare('SELECT * FROM hospital_appointments WHERE id=?').get(req.params.id); if (!a || a.status !== 'confirmed') return res.status(409).json({error:'Only confirmed appointments can check in.'}); const now = Date.now(); db.prepare("UPDATE hospital_appointments SET status='checked_in',checked_in_at=?,updated_at=? WHERE id=?").run(now,now,a.id); ensureVisitStages(a.id); db.prepare("UPDATE hospital_visit_stages SET status='completed',completed_at=?,updated_at=? WHERE appointment_id=? AND stage='registration'").run(now,now,a.id); event(a.id,'checked_in','confirmed','checked_in',actor(req)); recomputeQueue(a.doctor_id,isoDate(now)); res.json({appointment:appointmentRow(a.id)}); });
router.post('/queue/:id/:action', requirePerm('hospital:manage'), (req,res,next) => { const a = db.prepare('SELECT * FROM hospital_appointments WHERE id=?').get(req.params.id), action = req.params.action, transitions = {call:['checked_in','called'],complete:['called','completed'],skip:['checked_in','no_show']}; if (action === 'transfer') return next(); if (!a) return res.status(404).json({error:'Appointment not found.'}); if (!transitions[action] || a.status !== transitions[action][0]) return res.status(409).json({error:`Cannot ${action} this appointment.`}); const now = Date.now(), to = transitions[action][1], field = action === 'call' ? 'called_at' : action === 'complete' ? 'completed_at' : null; db.prepare(`UPDATE hospital_appointments SET status=?,${field ? `${field}=?,` : ''}updated_at=? WHERE id=?`).run(to,...(field ? [now] : []),now,a.id); event(a.id,action,a.status,to,actor(req)); notify(a.id,action === 'call' ? 'turn_alert':action,action === 'call' ? 'It is your turn. Please proceed to the consultation room.':`Appointment ${action}.`); recomputeQueue(a.doctor_id,isoDate(now)); res.json({appointment:appointmentRow(a.id)}); });
router.post('/queue/:id/transfer', requirePerm('hospital:manage'), (req,res) => { const a = db.prepare("SELECT * FROM hospital_appointments WHERE id=? AND status='checked_in'").get(req.params.id), doctorId = Number(req.body?.doctorId); if (!a || !doctorId || !db.prepare('SELECT id FROM hospital_doctors WHERE id=?').get(doctorId)) return res.status(400).json({error:'Checked-in appointment and destination doctor are required.'}); const now = Date.now(); db.prepare('UPDATE hospital_appointments SET doctor_id=?,updated_at=? WHERE id=?').run(doctorId,now,a.id); event(a.id,'transferred','checked_in','checked_in',actor(req),`Transferred to doctor ${doctorId}`); recomputeQueue(a.doctor_id,isoDate(now)); recomputeQueue(doctorId,isoDate(now)); notify(a.id,'transfer','Your consultation queue was transferred.'); res.json({appointment:appointmentRow(a.id)}); });
router.post('/appointments/:id/priority', requirePerm('hospital:manage'), (req,res) => { const a = db.prepare('SELECT * FROM hospital_appointments WHERE id=?').get(req.params.id), priority = req.body?.priority, reason = String(req.body?.reason || '').trim().slice(0,300); if (!a || !['normal','urgent'].includes(priority) || !reason) return res.status(400).json({error:'Appointment, valid priority, and reason are required.'}); db.prepare('UPDATE hospital_appointments SET priority=?,priority_reason=?,updated_at=? WHERE id=?').run(priority,reason,Date.now(),a.id); event(a.id,'priority_changed',a.priority,priority,actor(req),reason); recomputeQueue(a.doctor_id,isoDate(Date.now())); res.json({appointment:appointmentRow(a.id)}); });
router.get('/appointments/:id/history', requirePerm('hospital:manage'), (req,res) => res.json({events:db.prepare('SELECT * FROM hospital_queue_events WHERE appointment_id=? ORDER BY created_at DESC').all(req.params.id),notifications:db.prepare('SELECT * FROM hospital_notifications WHERE appointment_id=? ORDER BY created_at DESC').all(req.params.id)}));

export default router;
