import { useEffect, useState } from 'react';
import { Link, NavLink, Route, Routes, useSearchParams } from 'react-router-dom';
import QRCode from 'qrcode';

const NAME = import.meta.env.VITE_HOSPITAL_NAME || 'Your Hospital';
const TAGLINE = import.meta.env.VITE_HOSPITAL_TAGLINE || 'Trusted care, without the waiting uncertainty.';
const PHONE = import.meta.env.VITE_HOSPITAL_PHONE || 'Hospital contact number';
const EMERGENCY = import.meta.env.VITE_EMERGENCY_PHONE || 'your local emergency number';
const today = () => new Date().toISOString().slice(0,10);
const time = (value:number) => new Date(value).toLocaleTimeString([], { hour:'numeric',minute:'2-digit' });
async function api(method:string,path:string,body?:unknown) { const response = await fetch(path,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined}); const data = await response.json().catch(()=>({})); if(!response.ok) throw new Error(data.error||`Request failed (${response.status})`); return data; }

function Shell({children}:{children:React.ReactNode}) {
  return <><header><Link className="identity" to="/"><span className="cross">+</span><span><b>{NAME}</b><small>Patient services</small></span></Link><nav><NavLink to="/book">Appointments</NavLink><NavLink to="/manage">Manage visit</NavLink><NavLink to="/kiosk">Walk-in</NavLink><NavLink to="/board">Queue board</NavLink></nav><a className="staff" href="/login">Staff portal</a></header><main>{children}</main><footer><div><b>{NAME}</b><p>{TAGLINE}</p></div><div><b>Contact</b><p>{PHONE}</p></div><div><b>Important</b><p>For emergencies, call {EMERGENCY}.</p></div></footer></>;
}

function Home() {
  const [doctors,setDoctors]=useState<any[]>([]);
  useEffect(()=>{api('GET','/api/hospital/public/doctors').then(setDoctors).catch(()=>undefined)},[]);
  return <><section className="hero"><div className="hero-copy"><span className="eyebrow">Patient-first digital care</span><h1>Care that respects<br/><em>your time.</em></h1><p>{TAGLINE} Book a visit, check in on arrival, and follow your queue from one simple place.</p><div className="actions"><Link className="primary" to="/book">Book an appointment</Link><Link className="secondary" to="/manage">Manage my visit</Link></div><div className="trust"><span>✓ Secure booking</span><span>✓ Live queue updates</span><span>✓ Walk-in check-in</span></div></div><div className="hero-panel"><span className="pulse"/><small>Today’s patient services</small><div className="quick"><Link to="/check-in"><b>Arriving now?</b><span>Open check-in pass →</span></Link><Link to="/kiosk"><b>No appointment?</b><span>Join the walk-in queue →</span></Link><Link to="/board"><b>Already waiting?</b><span>View queue board →</span></Link></div></div></section><section className="emergency"><b>Emergency symptoms cannot wait for an online appointment.</b><span>Severe chest pain, breathing difficulty, heavy bleeding, stroke signs, loss of consciousness, or self-harm risk: contact {EMERGENCY} or hospital emergency services now.</span></section><section className="section"><div className="section-head"><span>OUR CLINICS</span><h2>Find the right care team</h2></div><div className="doctor-grid">{doctors.map(d=><article className="doctor" key={d.id}><div className="doctor-mark">{d.name.split(' ').slice(-1)[0]?.[0]}</div><div><h3>{d.name}</h3><p>{d.specialty}</p><small>{d.department} · {d.room || d.location}</small></div><Link to={`/book?doctor=${d.id}`}>View times</Link></article>)}{!doctors.length&&<p className="muted">The hospital is preparing its online schedule.</p>}</div></section><section className="steps"><div><span>01</span><h3>Choose care</h3><p>Select a doctor and a hospital-approved appointment time.</p></div><div><span>02</span><h3>Receive your pass</h3><p>Keep your booking code and QR check-in pass ready.</p></div><div><span>03</span><h3>Follow your turn</h3><p>Check in on arrival and receive a live queue estimate.</p></div></section></>;
}

function Booking() {
  const [params]=useSearchParams(); const [doctors,setDoctors]=useState<any[]>([]); const [doctorId,setDoctorId]=useState(params.get('doctor')||''); const [date,setDate]=useState(today()); const [slots,setSlots]=useState<any[]>([]); const [slotId,setSlotId]=useState(''); const [form,setForm]=useState({patientName:'',phone:'',email:'',reason:'',joinWaitlist:true}); const [result,setResult]=useState<any>(null); const [error,setError]=useState('');
  useEffect(()=>{api('GET','/api/hospital/public/doctors').then((rows:any[])=>{setDoctors(rows);if(!doctorId&&rows[0])setDoctorId(String(rows[0].id))}).catch(e=>setError(e.message))},[]);
  useEffect(()=>{if(!doctorId)return;setSlotId('');api('GET',`/api/hospital/public/slots?doctorId=${doctorId}&date=${date}`).then(setSlots).catch(e=>setError(e.message))},[doctorId,date]);
  async function submit(e:React.FormEvent){e.preventDefault();setError('');try{setResult(await api('POST','/api/hospital/public/bookings',{...form,doctorId:Number(doctorId),slotId:Number(slotId)}))}catch(err:any){setError(err.message)}}
  return <Page title="Book an appointment" intro="Choose your care team and an available hospital-approved time.">{result?<div className="success"><span>✓</span><h2>{result.appointment.status==='waitlisted'?'Waitlist request received':'Appointment confirmed'}</h2><p>Booking code <b>{result.appointment.booking_code}</b></p><p>{result.appointment.doctor_name} · {new Date(result.appointment.starts_at).toLocaleString()}</p><div className="actions"><Link className="primary" to={`/check-in?code=${result.appointment.checkin_code}`}>Open check-in pass</Link><Link className="secondary" to={`/manage?code=${result.appointment.booking_code}`}>Manage visit</Link></div></div>:<form onSubmit={submit}><div className="form-grid"><label>Doctor<select aria-label="Site doctor" value={doctorId} onChange={e=>setDoctorId(e.target.value)}>{doctors.map(d=><option value={d.id} key={d.id}>{d.name} — {d.specialty}</option>)}</select></label><label>Date<input aria-label="Site appointment date" type="date" min={today()} value={date} onChange={e=>setDate(e.target.value)}/></label></div><fieldset><legend>Available times</legend><div className="slots">{slots.map(s=><button className={slotId===String(s.id)?'selected':''} disabled={!s.available} type="button" onClick={()=>setSlotId(String(s.id))} key={s.id}>{time(s.starts_at)}<small>{s.service_type}</small></button>)}</div>{!slots.length&&<p className="muted">No online times are available on this date.</p>}</fieldset><div className="form-grid"><label>Patient name<input aria-label="Site patient name" required value={form.patientName} onChange={e=>setForm({...form,patientName:e.target.value})}/></label><label>Mobile number<input aria-label="Site patient phone" required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Email (optional)<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="wide">Reason for visit<textarea rows={3} value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label></div><label className="check"><input type="checkbox" checked={form.joinWaitlist} onChange={e=>setForm({...form,joinWaitlist:e.target.checked})}/> Join the waitlist if this time fills before confirmation</label>{error&&<p className="error">{error}</p>}<button className="primary" disabled={!slotId}>Confirm appointment</button></form>}</Page>;
}

function Manage() {
  const [params,setParams]=useSearchParams(); const [code,setCode]=useState(params.get('code')||''); const [visit,setVisit]=useState<any>(null); const [error,setError]=useState('');
  async function find(value=code){if(!value)return;setError('');try{const result=await api('GET',`/api/hospital/public/bookings/${encodeURIComponent(value)}`);setVisit(result.appointment);setParams({code:value})}catch(e:any){setVisit(null);setError(e.message)}}
  useEffect(()=>{if(params.get('code'))find(params.get('code')||'')},[]);
  async function cancel(){if(!window.confirm('Cancel this appointment?'))return;try{await api('POST',`/api/hospital/public/bookings/${code}/cancel`);await find()}catch(e:any){setError(e.message)}}
  return <Page title="Manage your visit" intro="Use the private booking code from your confirmation."><div className="lookup"><input aria-label="Site booking code" placeholder="APT-XXXXXX" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/><button className="primary" onClick={()=>find()}>Find visit</button></div>{error&&<p className="error">{error}</p>}{visit&&<div className="visit"><div><span className="status">{visit.status.replace('_',' ')}</span><h2>{visit.doctor_name}</h2><p>{visit.specialty} · {visit.location}</p><p>{visit.starts_at?new Date(visit.starts_at).toLocaleString():'Time pending'}</p>{visit.queue_number&&<p><b>Queue #{visit.queue_number}</b> · about {visit.estimated_wait_min} minutes</p>}</div><div className="actions">{visit.status==='confirmed'&&<Link className="primary" to={`/check-in?code=${visit.checkin_code}`}>Check-in pass</Link>}{visit.status==='confirmed'&&<button className="danger" onClick={cancel}>Cancel appointment</button>}</div></div>}</Page>;
}

function Checkin(){const[params]=useSearchParams();const[code,setCode]=useState(params.get('code')||'');const[qr,setQr]=useState('');const[result,setResult]=useState<any>(null);const[error,setError]=useState('');useEffect(()=>{if(code)QRCode.toDataURL(`${location.origin}/hospital-site/check-in?code=${encodeURIComponent(code)}`,{width:220,margin:1}).then(setQr)},[code]);async function checkin(){try{const data=await api('POST',`/api/hospital/public/bookings/${encodeURIComponent(code)}/check-in`);setResult(data.appointment)}catch(e:any){setError(e.message)}}return <Page title="Arrival check-in" intro="Open this pass when you reach the hospital.">{!params.get('code')&&<div className="lookup"><input aria-label="Site check-in code" placeholder="CHK-XXXXXX" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/></div>}{result?<div className="success"><span>✓</span><h2>You are checked in</h2><p className="queue-number">Queue #{result.queue_number}</p><p>Estimated wait: {result.estimated_wait_min} minutes</p></div>:<div className="pass">{qr&&<img src={qr} alt="Hospital check-in QR code"/>}<p>Reception can scan this QR pass, or you can check in below.</p>{error&&<p className="error">{error}</p>}<button className="primary" disabled={!code} onClick={checkin}>Check in now</button></div>}</Page>}

function Kiosk(){const[doctors,setDoctors]=useState<any[]>([]);const[doctorId,setDoctorId]=useState('');const[name,setName]=useState('');const[phone,setPhone]=useState('');const[reason,setReason]=useState('');const[result,setResult]=useState<any>(null);const[error,setError]=useState('');useEffect(()=>{api('GET','/api/hospital/public/doctors').then((rows:any[])=>{setDoctors(rows);if(rows[0])setDoctorId(String(rows[0].id))})},[]);async function join(e:React.FormEvent){e.preventDefault();try{const data=await api('POST','/api/hospital/public/walk-ins',{patientName:name,phone,reason,doctorId:Number(doctorId)});setResult(data.appointment)}catch(err:any){setError(err.message)}}return <Page title="Walk-in check-in" intro="For patients who have arrived without an appointment.">{result?<div className="success"><span>✓</span><h2>Check-in complete</h2><p className="queue-number">Queue #{result.queue_number}</p><p>Estimated wait: {result.estimated_wait_min} minutes</p><button className="secondary" onClick={()=>setResult(null)}>Check in another patient</button></div>:<form onSubmit={join}><label>Clinic<select aria-label="Site kiosk doctor" value={doctorId} onChange={e=>setDoctorId(e.target.value)}>{doctors.map(d=><option value={d.id} key={d.id}>{d.name} — {d.specialty}</option>)}</select></label><label>Patient name<input aria-label="Site kiosk patient" required value={name} onChange={e=>setName(e.target.value)}/></label><label>Mobile number<input value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Reason for visit<textarea rows={3} value={reason} onChange={e=>setReason(e.target.value)}/></label>{error&&<p className="error">{error}</p>}<button className="primary">Join queue</button></form>}</Page>}

function Board(){const[doctors,setDoctors]=useState<any[]>([]);const[doctorId,setDoctorId]=useState('');const[data,setData]=useState<any>(null);useEffect(()=>{api('GET','/api/hospital/public/doctors').then((rows:any[])=>{setDoctors(rows);if(rows[0])setDoctorId(String(rows[0].id))})},[]);useEffect(()=>{if(!doctorId)return;const load=()=>api('GET',`/api/hospital/public/display?doctorId=${doctorId}`).then(setData);load();const timer=setInterval(load,15000);return()=>clearInterval(timer)},[doctorId]);return <div className="board"><div className="board-top"><div className="identity"><span className="cross">+</span><b>{NAME}</b></div><select aria-label="Site board doctor" value={doctorId} onChange={e=>setDoctorId(e.target.value)}>{doctors.map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select></div><h1>Now serving</h1>{data&&<><h2>{data.doctor.name} · {data.doctor.room||data.doctor.location}</h2><div className="tokens">{data.queue.map((q:any)=><div className={q.status==='called'?'called':''} key={q.queue_number}><small>{q.status==='called'?'PLEASE PROCEED':'QUEUE'}</small><b>#{q.queue_number}</b><span>{q.status==='called'?'Now serving':`About ${q.estimated_wait_min} min`}</span></div>)}</div>{!data.queue.length&&<p className="board-empty">No patients currently waiting.</p>}<p className="privacy">Patient names are never displayed · Updates automatically</p></>}</div>}

function Page({title,intro,children}:{title:string,intro:string,children:React.ReactNode}){return <section className="page"><div className="page-title"><span>ONLINE PATIENT SERVICES</span><h1>{title}</h1><p>{intro}</p></div><div className="paper">{children}</div></section>}

export default function App(){return <Routes><Route element={<Shell><Routes><Route path="/" element={<Home/>}/><Route path="/book" element={<Booking/>}/><Route path="/manage" element={<Manage/>}/><Route path="/check-in" element={<Checkin/>}/><Route path="/kiosk" element={<Kiosk/>}/></Routes></Shell>} path="/*"/><Route path="/board" element={<Board/>}/></Routes>}
