import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../lib/api';

const FLAGS = [['difficulty_breathing','Difficulty breathing'],['chest_pain','Chest pain'],['severe_bleeding','Severe bleeding'],['loss_of_consciousness','Loss of consciousness'],['stroke_signs','Stroke signs'],['self_harm_risk','Self-harm risk']];
const day = () => new Date().toISOString().slice(0, 10);

export default function HospitalOperations() {
  const [doctors,setDoctors] = useState<any[]>([]); const [appointments,setAppointments] = useState<any[]>([]); const [appointmentId,setAppointmentId] = useState(''); const [stages,setStages] = useState<any[]>([]); const [note,setNote] = useState(''); const [flags,setFlags] = useState<string[]>([]); const [disposition,setDisposition] = useState('standard'); const [triageNote,setTriageNote] = useState(''); const [integration,setIntegration] = useState<any>(null); const [fhir,setFhir] = useState<any>(null); const [absence,setAbsence] = useState({ doctorId:'', substituteDoctorId:'', startsAt:`${day()}T09:00`, endsAt:`${day()}T17:00`, reason:'' });
  const load = async () => { try { const [docs, appts, int]: any = await Promise.all([api('GET','/api/hospital/doctors'),api('GET',`/api/hospital/appointments?date=${day()}`),api('GET','/api/hospital/integrations/status')]); setDoctors(docs); setAppointments(appts); setIntegration(int); setAppointmentId(current => current || String(appts[0]?.id || '')); setAbsence(current => ({...current,doctorId:current.doctorId || String(docs[0]?.id || ''),substituteDoctorId:current.substituteDoctorId || String(docs[1]?.id || '')})); } catch(e:any) { setNote(e.message); } };
  useEffect(() => { load(); }, []); useEffect(() => { if (appointmentId) api('GET',`/api/hospital/appointments/${appointmentId}/visit-stages`).then((data:any) => setStages(data.stages)).catch(e => setNote(e.message)); },[appointmentId]);
  async function triage() { try { await api('POST',`/api/hospital/appointments/${appointmentId}/triage`,{disposition,redFlags:flags,notes:triageNote}); setNote(`Triage recorded: ${disposition.replace('_',' ')}.`); } catch(e:any) { setNote(e.message); } }
  async function stage(stageName:string,action:string) { try { const data:any = await api('POST',`/api/hospital/appointments/${appointmentId}/visit-stages/${stageName}`,{action}); setStages(data.stages); setNote(`${stageName} updated.`); } catch(e:any) { setNote(e.message); } }
  async function createAbsence() { try { const data:any = await api('POST','/api/hospital/doctor-absences',{...absence,doctorId:Number(absence.doctorId),substituteDoctorId:absence.substituteDoctorId ? Number(absence.substituteDoctorId) : null,startsAt:new Date(absence.startsAt).getTime(),endsAt:new Date(absence.endsAt).getTime()}); setNote(`Absence saved: ${data.transferred} moved to substitute, ${data.needsRebooking} need rebooking.`); } catch(e:any) { setNote(e.message); } }
  async function sync(target:string) { try { await api('POST',`/api/hospital/appointments/${appointmentId}/sync`,{target}); setNote(`${target.toUpperCase()} received the appointment.`); } catch(e:any) { setNote(e.message); } }
  async function previewFhir() { try { setFhir(await api('GET',`/api/hospital/appointments/${appointmentId}/fhir`)); } catch(e:any) { setNote(e.message); } }
  return <><div className="top"><div><h1>🏥 Care operations</h1><div className="sub">Nurse triage · visit handoffs · doctor absence · HMIS/ABDM readiness</div></div><Link className="chip" to="/hospital">← Queue dashboard</Link></div>{note && <div className="card" style={{color:'var(--brand)'}}>{note}</div>}
    <div className="card"><label>Patient visit<select aria-label="Operations appointment" value={appointmentId} onChange={e=>setAppointmentId(e.target.value)}>{appointments.map(a=><option value={a.id} key={a.id}>{a.patient_name} · {a.doctor_name} · {a.status}</option>)}</select></label>{appointments.length===0&&<p className="muted">A checked-in or booked appointment is needed to operate this view.</p>}</div>
    <div className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(310px,1fr))'}}>
      <div className="card"><h3>Nurse triage</h3><p className="muted">Staff assessment only. Use your hospital emergency policy; this tool does not diagnose.</p><label>Disposition<select aria-label="Triage disposition" value={disposition} onChange={e=>setDisposition(e.target.value)}><option value="standard">Standard queue</option><option value="nurse_review">Nurse review</option><option value="emergency_escalation">Emergency escalation</option></select></label><div style={{marginTop:10}}>{FLAGS.map(([id,label])=><label key={id} style={{display:'block'}}><input type="checkbox" checked={flags.includes(id)} onChange={e=>setFlags(current=>e.target.checked?[...current,id]:current.filter(item=>item!==id))}/>{label}</label>)}</div><label>Staff note<textarea aria-label="Triage note" required={disposition==='emergency_escalation'} rows={3} value={triageNote} onChange={e=>setTriageNote(e.target.value)}/></label><button className="btn" disabled={!appointmentId} onClick={triage}>Record triage</button></div>
      <div className="card"><h3>Visit stages</h3><p className="muted">Track the patient between departments, not only the consultation queue.</p>{stages.map(s=><div className="feed-item" key={s.id}><div><b>{s.label}</b><div className="muted">{s.status}</div></div><div className="row">{s.status==='not_required'&&<button className="chip" onClick={()=>stage(s.stage,'require')}>Require</button>}{s.status==='waiting'&&<button className="chip" onClick={()=>stage(s.stage,'start')}>Start</button>}{s.status==='in_progress'&&<button className="chip" onClick={()=>stage(s.stage,'complete')}>Complete</button>}{['waiting','in_progress'].includes(s.status)&&<button className="chip" onClick={()=>stage(s.stage,'skip')}>Skip</button>}</div></div>)}</div>
      <div className="card"><h3>Doctor absence & substitute</h3><label>Absent doctor<select aria-label="Absent doctor" value={absence.doctorId} onChange={e=>setAbsence({...absence,doctorId:e.target.value})}>{doctors.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Substitute doctor<select aria-label="Substitute doctor" value={absence.substituteDoctorId} onChange={e=>setAbsence({...absence,substituteDoctorId:e.target.value})}><option value="">No substitute — request rebooking</option>{doctors.filter(d=>String(d.id)!==absence.doctorId).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>From<input aria-label="Absence start" type="datetime-local" value={absence.startsAt} onChange={e=>setAbsence({...absence,startsAt:e.target.value})}/></label><label>Until<input aria-label="Absence end" type="datetime-local" value={absence.endsAt} onChange={e=>setAbsence({...absence,endsAt:e.target.value})}/></label><label>Reason<input aria-label="Absence reason" value={absence.reason} onChange={e=>setAbsence({...absence,reason:e.target.value})}/></label><button className="btn" onClick={createAbsence}>Save absence & rebook</button></div>
      <div className="card"><h3>HMIS / ABDM interoperability</h3><p className="muted">FHIR R4 Appointment export is available now. Live exchange requires hospital-approved endpoints and ABDM onboarding.</p><p>HMIS: <b>{integration?.hmis.configured?'Connected':'Not configured'}</b><br/>ABDM: <b>{integration?.abdm.configured?'Connected':'Onboarding required'}</b></p><div className="row"><button className="chip" disabled={!appointmentId} onClick={previewFhir}>Preview FHIR</button><button className="chip" disabled={!appointmentId} onClick={()=>sync('hmis')}>Sync HMIS</button><button className="chip" disabled={!appointmentId} onClick={()=>sync('abdm')}>Sync ABDM</button></div>{fhir&&<pre aria-label="FHIR appointment preview" style={{whiteSpace:'pre-wrap',fontSize:11,maxHeight:280,overflow:'auto'}}>{JSON.stringify(fhir,null,2)}</pre>}</div>
    </div></>;
}
