import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../lib/api';

export default function HospitalKiosk() {
  const [doctors, setDoctors] = useState<any[]>([]); const [doctorId, setDoctorId] = useState(''); const [name, setName] = useState(''); const [phone, setPhone] = useState(''); const [reason, setReason] = useState(''); const [pass, setPass] = useState<any>(null); const [error, setError] = useState('');
  useEffect(() => { api('GET', '/api/hospital/public/doctors').then((rows: any) => { setDoctors(rows); if (rows[0]) setDoctorId(String(rows[0].id)); }).catch(e => setError(e.message)); }, []);
  async function join(event: React.FormEvent) { event.preventDefault(); setError(''); try { const out: any = await api('POST', '/api/hospital/public/walk-ins', { patientName: name, phone, reason, doctorId: Number(doctorId) }); setPass(out.appointment); } catch (e: any) { setError(e.message); } }
  return <div style={{ minHeight: '100vh', padding: '32px 6vw', maxWidth: 760, margin: 'auto' }}><div className="brand" style={{ marginBottom: 28 }}><span className="dot"/><span>MASystem Hospital · Kiosk</span></div><div className="card">{pass ? <div className="bubble"><h1>You are checked in</h1><p style={{ fontSize: 24 }}>Queue number <b>#{pass.queue_number}</b></p><p>Estimated wait: <b>{pass.estimated_wait_min} minutes</b></p><p className="muted">Please watch the waiting-room display and follow staff directions.</p><button className="btn" onClick={() => { setPass(null); setName(''); setPhone(''); setReason(''); }}>Check in another patient</button></div> : <form onSubmit={join}><h1>Walk-in check-in</h1><p className="muted">Choose the clinic and enter your name to receive a queue number.</p><label>Clinic / doctor<select aria-label="Kiosk doctor" value={doctorId} onChange={e => setDoctorId(e.target.value)}>{doctors.map(d => <option key={d.id} value={d.id}>{d.name} — {d.specialty}</option>)}</select></label><label>Patient name<input aria-label="Kiosk patient name" required value={name} onChange={e => setName(e.target.value)} /></label><label>Phone (for turn alerts)<input aria-label="Kiosk phone" value={phone} onChange={e => setPhone(e.target.value)} /></label><label>Reason for visit<textarea aria-label="Kiosk reason" rows={2} value={reason} onChange={e => setReason(e.target.value)} /></label>{error && <p style={{ color: 'var(--red)' }}>{error}</p>}<button className="btn" style={{ marginTop: 16 }}>Get queue number</button></form>}<div style={{ marginTop: 20 }}><Link to="/hospital/book">Book an appointment instead</Link></div></div></div>;
}
