import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../lib/api';

const WEEKDAYS = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

export default function HospitalConfiguration() {
  const [departments, setDepartments] = useState<any[]>([]); const [doctors, setDoctors] = useState<any[]>([]); const [policies, setPolicies] = useState<any[]>([]); const [holidays, setHolidays] = useState<any[]>([]); const [note, setNote] = useState('');
  const [department, setDepartment] = useState({ name: '', location: '' }); const [doctor, setDoctor] = useState({ name: '', specialty: '', departmentId: '', room: '', duration: '15' }); const [policy, setPolicy] = useState({ doctorId: '', weekday: '1', startTime: '09:00', endTime: '17:00', durationMin: '15', capacity: '1', serviceType: 'Consultation' }); const [holiday, setHoliday] = useState({ date: '', name: '' });
  const load = async () => { try { const [d, docs, p, h]: any = await Promise.all([api('GET', '/api/hospital/departments'), api('GET', '/api/hospital/doctors'), api('GET', '/api/hospital/slot-policies'), api('GET', '/api/hospital/holidays')]); setDepartments(d); setDoctors(docs); setPolicies(p); setHolidays(h); setDoctor(v => ({ ...v, departmentId: v.departmentId || String(d[0]?.id || '') })); setPolicy(v => ({ ...v, doctorId: v.doctorId || String(docs[0]?.id || '') })); } catch (e: any) { setNote(e.message); } };
  useEffect(() => { load(); }, []);
  async function submit(path: string, body: any, success: string) { try { await api('POST', path, body); setNote(success); await load(); } catch (e: any) { setNote(e.message); } }
  async function remove(path: string) { if (!window.confirm('Remove this configuration?')) return; try { await api('DELETE', path); await load(); } catch (e: any) { setNote(e.message); } }
  return <><div className="top"><div><h1>🏥 Hospital configuration</h1><div className="sub">Configure your own departments, rooms, doctors, closures, and booking-slot rules.</div></div><Link className="chip" to="/hospital">← Queue dashboard</Link></div>{note && <div className="card" style={{ color: 'var(--brand)' }}>{note}</div>}
    <div className="grid" style={{ gridTemplateColumns: 'repeat(auto-fit,minmax(290px,1fr))' }}>
      <form className="card" onSubmit={e => { e.preventDefault(); submit('/api/hospital/departments', department, 'Department added.'); setDepartment({ name: '', location: '' }); }}><h3>1. Departments & locations</h3><label>Department name<input aria-label="Department name" required value={department.name} onChange={e => setDepartment({ ...department, name: e.target.value })}/></label><label>Location / campus<input aria-label="Department location" required value={department.location} onChange={e => setDepartment({ ...department, location: e.target.value })}/></label><button className="btn" style={{ marginTop: 12 }}>Add department</button><div style={{ marginTop: 16 }}>{departments.map(d => <div className="feed-item" key={d.id}><div><b>{d.name}</b><div className="muted">{d.location}</div></div><button className="chip" type="button" onClick={() => remove(`/api/hospital/departments/${d.id}`)}>Remove</button></div>)}{departments.length === 0 && <p className="muted">Add your real departments first.</p>}</div></form>
      <form className="card" onSubmit={e => { e.preventDefault(); submit('/api/hospital/doctors', { ...doctor, departmentId: Number(doctor.departmentId), duration: Number(doctor.duration) }, 'Doctor added. Add the doctor’s slot policy next.'); setDoctor({ ...doctor, name: '', specialty: '', room: '' }); }}><h3>2. Doctors & rooms</h3><label>Doctor name<input aria-label="Configured doctor name" required value={doctor.name} onChange={e => setDoctor({ ...doctor, name: e.target.value })}/></label><label>Specialty<input aria-label="Configured specialty" required value={doctor.specialty} onChange={e => setDoctor({ ...doctor, specialty: e.target.value })}/></label><label>Department<select aria-label="Configured department" required value={doctor.departmentId} onChange={e => setDoctor({ ...doctor, departmentId: e.target.value })}>{departments.map(d => <option value={d.id} key={d.id}>{d.name}</option>)}</select></label><label>Consultation room<input aria-label="Configured room" required value={doctor.room} onChange={e => setDoctor({ ...doctor, room: e.target.value })}/></label><label>Default duration (minutes)<input aria-label="Configured duration" type="number" min="5" max="90" value={doctor.duration} onChange={e => setDoctor({ ...doctor, duration: e.target.value })}/></label><button className="btn" disabled={!departments.length} style={{ marginTop: 12 }}>Add doctor</button><div style={{ marginTop: 16 }}>{doctors.map(d => <div className="feed-item" key={d.id}><div><b>{d.name}</b><div className="muted">{d.department} · {d.room} · {d.default_duration_min} min</div></div></div>)}{doctors.length === 0 && <p className="muted">No doctors are bookable until you add them.</p>}</div></form>
      <form className="card" onSubmit={e => { e.preventDefault(); submit('/api/hospital/slot-policies', { ...policy, doctorId: Number(policy.doctorId), weekday: Number(policy.weekday), durationMin: Number(policy.durationMin), capacity: Number(policy.capacity) }, 'Slot policy saved. Future availability now follows this rule.'); }}><h3>3. Weekly slot policies</h3><label>Doctor<select aria-label="Policy doctor" required value={policy.doctorId} onChange={e => setPolicy({ ...policy, doctorId: e.target.value })}>{doctors.map(d => <option value={d.id} key={d.id}>{d.name} · {d.room}</option>)}</select></label><label>Day of week<select aria-label="Policy weekday" value={policy.weekday} onChange={e => setPolicy({ ...policy, weekday: e.target.value })}>{WEEKDAYS.map((name, index) => <option value={index} key={name}>{name}</option>)}</select></label><div className="row"><label>Start<input aria-label="Policy start time" type="time" value={policy.startTime} onChange={e => setPolicy({ ...policy, startTime: e.target.value })}/></label><label>End<input aria-label="Policy end time" type="time" value={policy.endTime} onChange={e => setPolicy({ ...policy, endTime: e.target.value })}/></label></div><div className="row"><label>Slot minutes<input aria-label="Policy duration" type="number" min="5" value={policy.durationMin} onChange={e => setPolicy({ ...policy, durationMin: e.target.value })}/></label><label>Patients/slot<input aria-label="Policy capacity" type="number" min="1" value={policy.capacity} onChange={e => setPolicy({ ...policy, capacity: e.target.value })}/></label></div><label>Service type<input aria-label="Policy service type" value={policy.serviceType} onChange={e => setPolicy({ ...policy, serviceType: e.target.value })}/></label><button className="btn" disabled={!doctors.length} style={{ marginTop: 12 }}>Add policy</button><div style={{ marginTop: 16 }}>{policies.map(p => <div className="feed-item" key={p.id}><div><b>{p.doctor_name} · {WEEKDAYS[p.weekday]}</b><div className="muted">{p.start_time}–{p.end_time} · {p.duration_min} min · cap {p.capacity} · {p.service_type}</div></div><button className="chip" type="button" onClick={() => remove(`/api/hospital/slot-policies/${p.id}`)}>Remove</button></div>)}</div></form>
      <form className="card" onSubmit={e => { e.preventDefault(); submit('/api/hospital/holidays', holiday, 'Holiday closure added; bookings are closed for that date.'); setHoliday({ date: '', name: '' }); }}><h3>4. Holidays & closures</h3><label>Closure date<input aria-label="Holiday date" required type="date" value={holiday.date} onChange={e => setHoliday({ ...holiday, date: e.target.value })}/></label><label>Closure name<input aria-label="Holiday name" required value={holiday.name} onChange={e => setHoliday({ ...holiday, name: e.target.value })}/></label><button className="btn" style={{ marginTop: 12 }}>Add closure</button><div style={{ marginTop: 16 }}>{holidays.map(h => <div className="feed-item" key={h.id}><div><b>{h.holiday_date}</b><div className="muted">{h.name}</div></div><button className="chip" type="button" onClick={() => remove(`/api/hospital/holidays/${h.id}`)}>Remove</button></div>)}{holidays.length === 0 && <p className="muted">No holiday closures configured.</p>}</div></form>
    </div></>;
}
