import { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { api } from '../lib/api';

export default function HospitalBoard() {
  const [params] = useSearchParams(); const [doctors, setDoctors] = useState<any[]>([]); const [doctorId, setDoctorId] = useState(params.get('doctorId') || ''); const [data, setData] = useState<any>(null);
  useEffect(() => { api('GET', '/api/hospital/public/doctors').then((rows: any) => { setDoctors(rows); if (!doctorId && rows[0]) setDoctorId(String(rows[0].id)); }); }, []);
  useEffect(() => { if (!doctorId) return; const load = () => api('GET', `/api/hospital/public/display?doctorId=${doctorId}`).then(setData).catch(() => undefined); load(); const timer = window.setInterval(load, 15_000); return () => window.clearInterval(timer); }, [doctorId]);
  return <main style={{ minHeight: '100vh', background: '#061826', color: 'white', padding: '5vh 8vw' }}><div className="row" style={{ justifyContent: 'space-between' }}><div><div className="brand"><span className="dot"/><span>MASystem Hospital</span></div><h1 style={{ fontSize: 'clamp(30px,5vw,60px)', marginTop: 30 }}>Now serving</h1></div><select aria-label="Display doctor" value={doctorId} onChange={e => setDoctorId(e.target.value)} style={{ maxWidth: 280 }}>{doctors.map(d => <option key={d.id} value={d.id}>{d.name} · {d.room || d.location}</option>)}</select></div>{data && <><h2 style={{ color: '#a9dfff' }}>{data.doctor.specialty} · {data.doctor.room || data.doctor.location}</h2><div className="grid" style={{ gridTemplateColumns: 'repeat(auto-fit,minmax(180px,1fr))', marginTop: 36 }}>{data.queue.map((q: any) => <div className="card" key={q.queue_number} style={{ textAlign: 'center', fontSize: 22, border: q.status === 'called' ? '3px solid #5eead4' : undefined }}><div className="muted">{q.status === 'called' ? 'PLEASE PROCEED' : 'QUEUE'}</div><b style={{ fontSize: 64 }}>#{q.queue_number}</b><div>{q.status === 'called' ? 'Now serving' : `About ${q.estimated_wait_min} min`}</div></div>)}</div>{data.queue.length === 0 && <p style={{ fontSize: 28, color: '#a9dfff' }}>No patients currently waiting.</p>}<p className="muted" style={{ marginTop: 36 }}>Updated automatically · Patient names are never shown</p></>}</main>;
}
