import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { api } from '../lib/api';

const today = () => new Date().toISOString().slice(0, 10);
const time = (value?: number) => value ? new Date(value).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' }) : 'To be confirmed';

export default function PublicHospitalVisit() {
  const [params, setParams] = useSearchParams(); const [code, setCode] = useState(params.get('code') || ''); const [appointment, setAppointment] = useState<any>(null); const [error, setError] = useState(''); const [note, setNote] = useState(''); const [doctors, setDoctors] = useState<any[]>([]); const [doctorId, setDoctorId] = useState(''); const [date, setDate] = useState(today()); const [slots, setSlots] = useState<any[]>([]); const [slotId, setSlotId] = useState('');
  async function lookup(value = code) { if (!value.trim()) return; setError(''); try { const result: any = await api('GET', `/api/hospital/public/bookings/${encodeURIComponent(value.trim())}`); setAppointment(result.appointment); setCode(value.trim()); setParams({ code: value.trim() }); } catch (e: any) { setAppointment(null); setError(e.message); } }
  useEffect(() => { if (params.get('code')) lookup(params.get('code') || ''); }, []);
  useEffect(() => { api('GET', '/api/hospital/public/doctors').then((rows: any) => { setDoctors(rows); if (rows[0]) setDoctorId(String(rows[0].id)); }).catch(() => undefined); }, []);
  useEffect(() => { if (!doctorId) return; api('GET', `/api/hospital/public/slots?doctorId=${doctorId}&date=${date}`).then((rows: any) => setSlots(rows)).catch(() => setSlots([])); }, [doctorId, date]);
  async function cancel() { if (!appointment || !window.confirm('Cancel this appointment?')) return; try { await api('POST', `/api/hospital/public/bookings/${code}/cancel`); setNote('Your appointment was cancelled.'); lookup(); } catch (e: any) { setError(e.message); } }
  async function reschedule() { if (!slotId) return; try { const out: any = await api('POST', `/api/hospital/public/bookings/${code}/reschedule`, { doctorId: Number(doctorId), slotId: Number(slotId) }); setAppointment(out.appointment); setNote('Your appointment has been rescheduled.'); setSlotId(''); } catch (e: any) { setError(e.message); } }
  return <div style={{ minHeight: '100vh', padding: '28px 6vw', maxWidth: 780, margin: '0 auto' }}><div className="brand" style={{ marginBottom: 30 }}><span className="dot"/><span>MASystem Hospital</span></div><div className="card"><h1>Manage your visit</h1><p className="muted">Enter your booking code to see your appointment, check in when you arrive, or reschedule.</p><div className="row"><input aria-label="Booking code" placeholder="APT-XXXXXX" value={code} onChange={e => setCode(e.target.value.toUpperCase())}/><button className="btn" onClick={() => lookup()}>Find booking</button></div>{error && <p style={{ color: 'var(--red)' }}>{error}</p>}{note && <p style={{ color: 'var(--ok)' }}>{note}</p>}{appointment && <div className="bubble" style={{ marginTop: 18 }}><h3>{appointment.status === 'waitlisted' ? 'Waitlist request' : 'Your appointment'}</h3><p><b>{appointment.doctor_name}</b> · {appointment.specialty}</p><p>{time(appointment.starts_at)} · {appointment.location}</p><p>Status: <span className="pill">{appointment.status}</span>{appointment.queue_number ? ` · Queue #${appointment.queue_number}, about ${appointment.estimated_wait_min} min` : ''}</p>{['confirmed', 'checked_in'].includes(appointment.status) && <p className="muted">Check-in pass: <Link to={`/hospital/check-in?code=${appointment.checkin_code}`}>open your arrival pass</Link></p>}{appointment.status === 'confirmed' && <><button className="chip" onClick={cancel}>Cancel appointment</button><div style={{ borderTop: '1px solid var(--line)', marginTop: 18, paddingTop: 14 }}><b>Reschedule</b><div className="grid" style={{ gridTemplateColumns: 'repeat(auto-fit,minmax(170px,1fr))', marginTop: 10 }}><label>Doctor<select aria-label="New doctor" value={doctorId} onChange={e => setDoctorId(e.target.value)}>{doctors.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Date<input aria-label="New date" type="date" min={today()} value={date} onChange={e => setDate(e.target.value)}/></label></div><div className="row" style={{ marginTop: 10 }}>{slots.map(s => <button className={`chip ${slotId === String(s.id) ? 'on' : ''}`} type="button" disabled={!s.available} onClick={() => setSlotId(String(s.id))} key={s.id}>{new Date(s.starts_at).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}</button>)}</div><button className="btn" style={{ marginTop: 12 }} disabled={!slotId} onClick={reschedule}>Confirm new time</button></div></>}</div>}<div style={{ marginTop: 22 }}><Link to="/hospital/book">← Book a new appointment</Link></div></div></div>;
}
